name: Tests

on:
  push:
    branches: [master, develop]
    tags: [v*]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          channels: conda-forge,defaults
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Lint
        shell: bash -l {0}
        run: |
            conda install flake8
            python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        shell: bash -l {0}
        run: |
            pip install --upgrade pip
            pip install setuptools
            pip install wheel
            pip install cython
            pip install pandas==1.1.4
            pip install -r requirements/requirements.txt
            pip install -r requirements/docs.txt
            pip install --upgrade pytest flake8 sphinx --user
            pip install scipy --force-reinstall # for https://github.com/conda/conda/issues/6396
            conda install pytest
            python -m pytest tests --cov-report=xml --cov=delve -vvv
      - name: Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: false
